<?php
$API_KEY = 'b7fAIh1aBSkWVN26iVe1o3Sbu';
$API_KEY_SECRET = '3pWPuIhOV57PL0LPL3F3TO5yiiw6mMwrRUzcYVbd4XSSYsZsWQ';
$ACCESS_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAOpSVQEAAAAAHxXl57plinhQ2va7JhTvWzaeACs%3DzLBwdukgubrRcHzeTXuIPieu5qvlV25CZDXGrWuLG4XotosnNQ';